version: '3.7'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.102:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.102:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"